### ISSUE TITLE
Create a new version.

### ISSUE THREAD

**Issue by sirplatypos** [darshanparajuli/calc#1]
Hi,
I'm trying to submit this as a package for Gentoo, but it would be much better if you could take the last few commits and make a new version out of them so that it has the help function.
Thanks in advance.

**Comment by darshanparajuli** [comment]
Hi, 
I have tagged a new release `0.1.1` with the help function. Thanks!

**Comment by sirplatypos** [comment]
Thank you.   I would suggest also pushing to crates.io, but that's up to you.  Thank you for the commit, this will make things much easier.
